---
title: "Recursive Long-run Variance Estimation"
output: html_document
author: LEUNG Man Fung, Heman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Main
1. General and Super-optimal Recursive Estimators of Long-run Variance  
Available upon request.  

2. Supplement to General and Super-optimal Recursive Estimators of Long-run Variance  
Available upon request.  

3. [Diagnosing Learning Algorithms with Super-optimal Recursive Estimators](poster.pdf)  
Poster presentation at ICSA 2020 Applied Statistics Symposium.  

4. rlaser: an R package for Recursive Long-run Variance Estimation  
Available upon request.  

## Related Materials
1. [Reading Group - Asymptotic theory for stationary processes](Reading Group - Asymptotic theory for stationary processes.pdf)  
Wu ([2005](https://www.pnas.org/content/102/40/14150), [2011](https://www.intlpress.com/site/pub/pages/journals/items/sii/content/vols/0004/0002/a015/index.php)) developed a beautiful and coherent asymptotic framework for the inference of stationary process. Apart from using them in this research, I am also delighted to share them with other members of our research group.  

2. [Reading Group - Recursive Estimation of Time-Average Variance Constants](Reading Group - Recursive Estimation of Time-Average Variance Constants.pdf)  
This seminal paper by [Wu (2009)](https://projecteuclid.org/euclid.aoap/1248700626) enlightens us about recursive estimation of long-run variance. Along with [Chan and Yau (2017)](https://sites.google.com/site/kwchankeith/publications/rtacm), I detail the proofs and summarize some important ideas/techniques for this research.  

3. [Comparison of 'Pass by Reference' in R](Pass-by-Reference.html)  
In writing recursive functions, we frequently need to modify some local variables permanently for future iterations. As native R does not provide pointer, we investigate several available solutions for our package.  