---
title: "RMSC5102 Resources"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Spring, 2020

### Notes
1. [Tutorial notes](notes.pdf)  
2. [Midterm review](2020S/review_midterm.pdf)  

### Q&A
1. [Inverse transform](2020S/QA-Inverse-Transform.html)  
2. [Discrete uniform](2020S/QA-Discrete-Uniform.html)  
3. [Monte Carlo integration](2020S/QA-Monte-Carlo-Integration.html)

### Extra Exercise
1. [Stochastic calculus](2020S/EX-Stochastic-Calculus.html)

### Online Reference
1. [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/)  
Rmd is very useful if you want to incorporate R, LaTeX or other languages like Python in the same documentation. You can use it for your HW  
2. [R Programming for Data Science](https://bookdown.org/rdpeng/rprogdatascience/)  
If you want to learn more about R after reading the guide provided by our professors, you may try this. It also gives an introduction to vectorization which I sometimes use in our tutorials  
3. [Monte Carlo Tree Search](https://www.youtube.com/watch?v=UXW2yZndl7U)  
It is actually possible to apply simulation in AI development. One of the methods is Monte Carlo Tree Search. This video explains one particular algorithm called UCT with step-by-step illustration